export const DEFECT_CLASSES = [
  'crazing',
  'inclusion',
  'patches',
  'pitted_surface',
  'rolled_in_scale',
  'scratches',
] as const;

export type DefectClass = (typeof DEFECT_CLASSES)[number];

/** Bounding box in source-image pixels. */
export interface BBox {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Detection {
  id: string;
  cls: DefectClass;
  confidence: number; // 0..1
  box: BBox;
}

export interface Frame {
  id: string;
  stationId: string;
  imageUrl: string;
  width: number;
  height: number;
  capturedAt: string; // ISO
  detections: Detection[];
}

export type StationStatus = 'online' | 'degraded' | 'offline';

export interface Station {
  id: string;
  name: string;
  status: StationStatus;
  latencyMs: number;
  fps: number;
}

export interface DefectRow extends Detection {
  frameId: string;
  stationId: string;
  capturedAt: string;
}

export interface DefectPage {
  items: DefectRow[];
  total: number;
}

export interface Stats {
  inspected: number;
  defective: number;
  defectRate: number; // 0..1
  byClass: Record<DefectClass, number>;
}

export interface DefectFilters {
  cls: DefectClass[];
  stationId: string | null;
  from: string | null; // ISO
  to: string | null; // ISO
  page: number;
  pageSize: number;
}

/** One entry of src/mocks/manifest.json (generated by scripts/build_manifest.py). */
export interface ManifestEntry {
  id: string;
  file: string;
  width: number;
  height: number;
  boxes: Array<BBox & { cls: DefectClass }>;
}
